app = 'minha-vm-python'
primary_region = 'ams'

[build]
  image = "ubuntu:22.04"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 2222
